version: "3.8"

services:
  consumer:
    restart: on-failure
    image: link_consumer
    build:
      context: .
      dockerfile: ./Jobs.LinkConsumer/Dockerfile
    links:
      - db
      - rabbitmq
    depends_on:
      - rabbitmq
      - server

  server:
    image: docker_test_backend
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: ./DockerTest.Web/Dockerfile
    links:
      - db
      - rabbitmq
    volumes:
      - ./files/:/app/wwwroot/files/
    depends_on:
      - rabbitmq

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dockerTestDB
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/pg/:/var/lib/postgresql/data/
    ports:
      - 127.0.0.1:5432:5432

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "hackerdmitry"
      RABBITMQ_DEFAULT_PASS: "e2b72411-ebb9-40ab-8add-40f6fab4fce5"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 6